# Dependencies for development environment
version: "3.8"

#
# WARNING: Do not use this docker compose file in production. It is meant to for development only!
#
# Please use the released version of docker-compose.yml file:
#

services:
  db-dev:
    image: postgres:latest
    volumes:
      - ./dev-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fkadeal-data-sense-dev
      - POSTGRES_PASSWORD=DataSensePass
      - POSTGRES_DB=fkadeal-data-sense-dev-db
    ports:
      - 5432:5432

  vector-db-dev:
    image: chromadb/chroma:latest
    volumes:
      # Default configuration for persist_directory is "/chroma/chroma/"
      - ./dev-data/vector-db:/chroma/chroma/
    ports:
      - 8001:8000

  message-broker-dev:
    image: rabbitmq:management
    volumes:
      - ./dev-data/message-broker:/var/lib/rabbitmq
    hostname: "rabbit-host"
    ports:
      - 5672:5672
      - 15672:15672
